### ISSUE TITLE
How To prevent Multiple upload

### ISSUE THREAD

**Issue by developer-smartchain** [raunak811/angular-file-drag-drop#2]
can you add @input multiple="false" option 
 <ng-file-drag-drop                        
     [multiple]="false"
     (uploadedFiles)="getUploadedFiles($event)"
     [fileConfig]="dragDropConfig"
      >
  </ng-file-drag-drop>
like this

**Comment by raunak811** [comment]
Thanks, I have merged your PR

**Comment by paresh175** [comment]
hi @raunak811 , can you publish this changes in npm?

Thanks.
